name: JIRA Autolink Action
on:
  workflow_call:
  
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  link_ticket:
    name: Link Ticket
    runs-on: ubuntu-latest
    steps:
      - name: Clean title
        id: clean_title
        run: echo "title=$( echo '${{ github.event.pull_request.title }}' | sed 's/[A-Za-z][A-Za-z]*\s*[\/-]*[0-9][0-9]*[\/-:]*\s//')"
      - name: Check for Ticket
        id: check-for-ticket
        run: |
          if [[ ${{ github.head_ref }} =~ ^[A-Za-z]+-[0-9]+ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - uses: the-wright-jamie/update-pr-info-action@v1
        if: steps.check-for-ticket.outputs.match == 'true'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          title-update-action: 'replace'
          head-branch-regex: '^[A-Za-z]+-[0-9]+'
          title-template: '%headbranch%: ${{ steps.clean_title.outputs.title }}'
          body-template: |
            [JIRA Link: %headbranch%](https://flocasts.atlassian.net/browse/%headbranch%)
            ---
          body-update-action: 'prefix'
          body-uppercase-base-match: false
